# Generated by Django 4.0.5 on 2022-06-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sidebarimage',
            field=models.ImageField(default='', upload_to='Home/'),
            preserve_default=False,
        ),
    ]
