# Generated by Django 4.0.5 on 2022-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_home_sidebarimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='logo',
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
