# Generated by Django 4.0.5 on 2022-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_portfolio_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': '10 - Social_Profile',
            },
        ),
    ]
